
# launch devenv container
# -d pour detached
up:
	docker-compose up -d

down:
	docker-compose down

# rebuild docker image based on Dockerfile
build:
	docker compose build

# remove-container:
# docker compose rm -s back